#!/usr/bin/env bash
cd Titanic
echo -e "\e[33m        |   |    \e[0m"
echo -e "\e[33m        |   |         \e[0m"
echo -e "\e[33m        |   |         \e[0m"
echo -e "\e[33m        |   |_____   \e[0m"
echo -e "\e[33m        |______ /    \e[0m"
while(true) do
lua start.lua 
done
